# -*- coding: utf-8 -*-
"""Amanda - binary correlation testing assumptions - heatmap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kF-tnx1ysB5LLtQzClX2fR3VPSfp_-S0
"""

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn import preprocessing

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from matplotlib import pyplot as plt

import seaborn as sns

"""# New Section"""

table = pd.read_csv("data/polling_site_data/clean_precincts_with_polling_site.csv")
table.head()

"""In the section below, a heatmap is created to test whether there is multicollinearity between the independent variables.Correlation between the independent variables will range from 0 to 1, with 1 being the highest level of correlation.[(Leavitt, 2019)](https://https://towardsdatascience.com/multicollinearity-why-is-it-a-problem-398b010b77ac)


"""

plt.figure(figsize = (38,16))
sns.heatmap(table.corr(), annot = True)
plt.savefig('heatmap.png')
plt.show()